version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: producer/
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - kafka

  no-retry-consumer:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.NoRetryConsumer"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 20
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka

  limited-retries-consumer:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.LimitedRetriesConsumer"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 20
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka

  limited-retries-consumer2:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.Main"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 20
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka

  infinite-retries-consumer:
    build: consumer/
    environment:
      MAIN_CLASS: "com.sample.InfiniteRetriesConsumer"
      PERCENTAGE_FAILURES: 10
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_POLL_RECORDS: 10
      KAFKA_MAX_POLL_INTERVAL_MS: 10000
    depends_on:
      - kafka

  connect:
    build: connector/
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: "connect"
      CONNECT_CONFIG_STORAGE_TOPIC: connect.config
      CONNECT_OFFSET_STORAGE_TOPIC: connect.offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect.status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: "/usr/share/custom-connectors"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      PERCENTAGE_FAILURES: 10
    ports:
      - "8083:8083"
    depends_on:
      - kafka